version: '3.9'
services:
  deno-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-data-analyzer
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_HOST_ADRESS=${MONGODB_HOST_ADRESS}
      - MONGODB_HOST_PORT=${MONGODB_HOST_PORT}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_ADMIN_USER=${MONGODB_ADMIN_USER}
      - MONGODB_ADMIN_PASS=${MONGODB_ADMIN_PASS}
    depends_on:
      - mongo-db
    volumes:
      - .:/app
    command: ["deno", "task", "start"]
  
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASS}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
