// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_data_index from "./routes/api/data/index.ts";
import * as $api_dbcheck from "./routes/api/dbcheck.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $data_chart from "./routes/data/chart.tsx";
import * as $data_index from "./routes/data/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LiveDeviceData from "./islands/LiveDeviceData.tsx";
import * as $LiveRequestData from "./islands/LiveRequestData.tsx";
import * as $LiveSensorCharts from "./islands/LiveSensorCharts.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/data/index.ts": $api_data_index,
    "./routes/api/dbcheck.ts": $api_dbcheck,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/data/chart.tsx": $data_chart,
    "./routes/data/index.tsx": $data_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LiveDeviceData.tsx": $LiveDeviceData,
    "./islands/LiveRequestData.tsx": $LiveRequestData,
    "./islands/LiveSensorCharts.tsx": $LiveSensorCharts,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
